config/routes.rb
Rails.application.routes.draw do
  root 'site#index'

  resources :movies

  get '/contact' => 'inquiries#new'
  post '/contact' => 'inquiries#create'

  get '/about' => 'site#about'
  get '/privacy' => 'site#privacy'
  get '/terms' => 'site#terms'

end

app/models/inquiry.rb
class Inquiry
  include Mongoid::Document

  field :name, type: String
  field :email, type: String
  field :subject, type: String
  field :message, type: String

  validates :email, presence: true
  validates :subject, presence: true,
    length: { in: 4..32 }
  validates :message, presence: true,
    length: { minimum: 12 }
end

app/models/movie.rb
class Movie
  include Mongoid::Document

  field :title, type: String
  field :director, type: String
  field :genre, type: String
  field :year, type: Integer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inquiries_controller.rb
class InquiriesController < ApplicationController
  def new
    @inquiry = Inquiry.new
  end

  def create
    @inquiry = Inquiry.create(inquiry_params)

    if (@inquiry.valid?)
      InquiryMailer.inquiry_email(@inquiry).deliver_now

      flash[:notice] = "Thank you for sending us a message, #{@inquiry.name}"
      redirect_to root_url
    else
      render :new
    end
  end

  private

  def inquiry_params
    params.require(:inquiry).permit( :name, :email, :subject, :message )
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController


  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.create(movie_params)

    if (@movie.valid?)
      flash[:notice] = "Thank you! #{@movie.title} has been added."
      redirect_to new_movie_path
    else
      render :new
    end
  end

  def index
    @movies = Movie.all.to_a
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])

    if (@movie.update(movie_params))
      flash[:notice] = "Thank you! #{@movie.title} has been updated."
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_url
  end


  private

  def movie_params
    params.require(:movie).permit(:title, :director, :genre, :year)
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  def index
    @title = "Welcome!"
  end

  def about
  end

  def privacy
  end

  def terms
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/inquiries/new.html.erb
<% if @inquiry.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@inquiry.errors.count, "issue") %> prevented your message from being sent:
    </h2>

    <ul>
    <% @inquiry.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class="row">
  <div class="col-sm-6">
    <%= form_for @inquiry, url: contact_path do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :subject %>
        <%= f.text_field :subject, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :message %>
        <%= f.text_area :message, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit "Send message", class: "btn btn-info btn-sm" %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title || "TDC Rules!" %></title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all' %>

    <%= javascript_include_tag 'application' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  </head>
  <body>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%=
            link_to_unless_current "Enspiral Dev Academy",
              root_path, class: "navbar-brand" do |label|
                content_tag(:span, label, class: "navbar-brand")
              end
          %>
        </div>
          <div id="navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
              <li><%= link_to_unless_current "About", about_path do
                content_tag(:span, "About", class: "this-page")
              end %></li>
            <li>
              <%= link_to_unless_current "Contact", contact_path do |label|
                content_tag(:span, label, class: "this-page")
              end %>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <!-- Begin page content -->
    <main class="container main" role="main">
        <% if flash.alert %>
          <div class="messages">
            <div class="alert alert-danger" role="alert">
              <%= flash.alert %>
            </div>
          </div>
        <% end %>

      <% if flash.notice %>
        <div class="messages">
          <div class="alert alert-success" role="alert">
            <%= flash.notice %>
          </div>
        </div>
      <% end %>

      <%= yield %>
    </main>

    <footer class="footer">
      <div class="container">
        <nav class="pull-right">
          <%= link_to_unless_current "Privacy policy", privacy_path do |label|
            content_tag(:span, label, class: "this-page")
          end %> &middot;
          <%= link_to_unless_current "Terms of use", terms_path do |label|
            content_tag(:span, label, class: "this-page")
          end %>
        </nav>
        <p class="text-muted copyright">&copy; 2015 Enspiral Dev Academy. Yeah.</p>
      </div>
    </footer>

  </body>
</html>

app/views/movies/edit.html.erb
<% if @movie.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@movie.errors.count, "issue") %> prevented your movie from being updated:</h2>

    <ul>
    <% @movie.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<article>
  <header class="page-header">
    <h1>Edit movie</h1>
  </header>
  <div class="row">
    <div class="col-sm-6">
      <%= form_for @movie do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :director %>
          <%= f.text_field :director, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :genre %>
          <%= f.text_field :genre, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :year %>
          <%= f.number_field :year, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit class: "btn btn-info btn-sm" %>
        </div>
      <% end %>
    </div>
  </div>
</article>

app/views/movies/index.html.erb
<article>
  <header class="page-header">
    <h1>Movies</h1>
  </header>
  <ul>
    <% @movies.each do |movie| %>
      <li><%= movie.title %></li>
    <% end %>
  </ul>
</article>

app/views/movies/new.html.erb
<% if @movie.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@movie.errors.count, "issue") %> prevented your movie from being added:</h2>

    <ul>
    <% @movie.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<article>
  <header class="page-header">
    <h1>Add a new movie</h1>
  </header>
  <div class="row">
    <div class="col-sm-6">
      <%= form_for @movie do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :director %>
          <%= f.text_field :director, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :genre %>
          <%= f.text_field :genre, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :year %>
          <%= f.number_field :year, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit class: "btn btn-info btn-sm" %>
        </div>
      <% end %>
    </div>
  </div>
</article>

app/views/movies/show.html.erb
<article>
  <header class="page-header">
    <h1><%= @movie.title %></h1>
  </header>
  <dl>
    <dt>Director</dt>
    <dd><%= @movie.director %></dd>
    <dt>Genre</dt>
    <dd><%= @movie.genre %></dd>
    <dt>Year</dt>
    <dd><%= @movie.year %></dd>
  </dl>
</article>

app/views/site/about.html.erb
<article>
  <header class="page-header">
    <h1>About us</h1>
  </header>
  <p>Here you can learn all about us!</p>
</article>

app/views/site/index.html.erb
<article>
  <header class="page-header">
    <h1><%= @title %></h1>
  </header>
  <p>Welcome to our brave new site!</p>
</article>

app/views/site/privacy.html.erb
<article>
  <header class="page-header">
    <h1>Our privacy policy</h1>
  </header>
  <p>We respect your privacy. Really!</p>
</article>

app/views/site/terms.html.erb
<article>
  <header class="page-header">
    <h1>Our terms of use</h1>
  </header>
  <p>You should respect our terms of use. Really!</p>
</article>